In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, f1_score

In [15]:
df = pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [16]:
df.shape

(284807, 31)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [18]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [19]:
df.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.168375e-15  3.416908e-16 -1.379537e-15  2.074095e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   9.604066e-16  1.487313e-15 -5.556467e-16  1.213481e-16 -2.406331e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.654067e-16 -3.568593e-16  2.578648e-16  4.473266e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.340915e-16  1.683437e-15 -3.660091e-16 -1.227390e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [30]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [38]:
#under sampling
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

legit_df = legit.sample(n=492)

In [40]:
legit_df

Time        V1        V2        V3        V4        V5        V6  \
120223   75752.0  1.177170  0.602012 -0.477907  0.750399  0.304530 -0.767118   
24604    33298.0  1.170401 -0.760061  0.038898 -0.774159 -0.783066 -0.669695   
279674  169020.0 -0.791166  0.144833 -0.329066 -2.046475  0.371384  0.319418   
128448   78713.0  1.082175 -0.771596  0.411920 -0.047716 -0.456000  0.911210   
265999  162140.0  2.119862 -0.085867 -1.504011  0.176504  0.377032 -0.610117   
...          ...       ...       ...       ...       ...       ...       ...   
12537    21938.0  1.127649 -0.455750  1.092144 -0.618548 -1.113201 -0.125422   
30040    35749.0 -0.717922  0.061244  0.991997 -1.507883 -1.383475 -0.176132   
232024  147015.0 -1.237494  1.567535 -0.344661 -0.398707  0.013889 -0.976716   
197951  132251.0  2.142213 -1.654778 -1.362108 -1.754179 -0.816246  0.029324   
147414   88521.0  1.739403 -1.579715  0.141292 -0.130107 -1.625467  0.373133   

              V7        V8        V9  ...       V21       V22       V23  \
120223  0.270819 -0.076067 -0.525999  ... -0.055037 -0.077386 -0.047619   
24604  -0.214580 -0.141822 -1.238322  ... -0.186472 -0.999261  0.053307   
279674  0.350928  0.553814 -1.325139  ...  0.074365  0.338638 -0.277141   
128448 -0.658235  0.278647  1.342107  ... -0.244702 -0.636591 -0.142793   
265999  0.190441 -0.284845  0.573746  ... -0.349754 -0.874254  0.201482   
...          ...       ...       ...  ...       ...       ...       ...   
12537  -0.913032  0.227834  3.018919  ... -0.078103  0.183211  0.023883   
30040  -0.345987  0.563785  1.165757  ...  0.328286  1.038399  0.153424   
232024  0.609775  0.003569  0.282732  ...  0.003647 -0.245725  0.175367   
197951 -0.998098 -0.134070 -1.513344  ... -0.021259  0.302667 -0.059623   
147414 -1.400895  0.199083  0.166947  ... -0.016999  0.250125  0.114512   

             V24       V25       V26       V27       V28  Amount  Class  
120223  0.127017  0.458872  0.366731 -0.014234  0.032505    0.76      0  
24604  -0.029293  0.170141 -0.650793 -0.034141  0.026664  130.00      0  
279674 -0.407979  0.433601 -0.097638 -0.043522  0.040038   79.00      0  
128448 -1.246608  0.202921  1.049719 -0.039521  0.012646  104.00      0  
265999 -0.996368 -0.154166  0.258678 -0.072001 -0.068512    9.99      0  
...          ...       ...       ...       ...       ...     ...    ...  
12537   0.153100  0.300316 -0.722464  0.069543  0.016531   11.85      0  
30040   0.062392 -0.767626  0.107663  0.030420  0.085216   86.99      0  
232024 -0.020014 -0.960835  0.150758 -0.694156  0.231597    4.38      0  
197951 -1.128443 -0.007961 -0.025715 -0.001275 -0.055411  108.50      0  
147414 -0.395014 -0.635404  0.318923  0.021817 -0.011085  164.95      0  

[492 rows x 31 columns]

In [46]:
new_df = pd.concat([legit_df, fraud], axis = 0)
new_df = new_df.sample(frac=1, random_state=42).reset_index(drop=True)

In [48]:
new_df

Time         V1        V2         V3        V4        V5        V6  \
0     41233.0 -10.645800  5.918307 -11.671043  8.807369 -7.975501 -3.586806   
1    114349.0   0.144010  1.084010  -0.426590 -0.572116  1.070631 -0.772620   
2     72327.0  -4.198735  0.194121  -3.917586  3.920748 -1.875486 -2.118933   
3    103539.0   1.966257 -0.752139  -0.348350 -0.391010 -0.995474 -0.749373   
4     45946.0  -2.012939  1.638347   0.041331 -1.273283 -0.971181 -0.754507   
..        ...        ...       ...        ...       ...       ...       ...   
979  162743.0  -0.013475  0.796912   0.354508 -0.674715  0.429000 -0.872184   
980    1409.0  -2.586169 -1.073040   2.392480 -3.280437 -0.185766  2.251754   
981  128471.0   0.909124  1.337658  -4.484728  3.245358 -0.417809 -0.762119   
982  155624.0  -2.205711  0.905868  -0.284922 -3.348072 -0.607188 -0.811110   
983  143886.0  -0.239666  1.760283  -1.140414  1.003040  1.190820 -0.115147   

            V7        V8        V9  ...       V21       V22       V23  \
0   -13.616797  6.428169 -7.368451  ...  2.571970  0.206809 -1.667801   
1     1.010791 -0.152443 -0.173262  ... -0.338319 -0.782779  0.069414   
2    -3.614445  1.687884 -2.189871  ...  0.801312 -0.183001 -0.440387   
3    -0.790460 -0.161623  3.167487  ...  0.069238  0.600572  0.087117   
4    -0.568182  1.386204 -0.432341  ...  0.123206  0.040243  0.248554   
..         ...       ...       ...  ...       ...       ...       ...   
979   0.882522 -0.056498 -0.287547  ... -0.204209 -0.453735  0.068320   
980  -2.178799 -1.620027  2.757823  ... -1.044110  1.921347 -0.379853   
981  -2.506349  0.694164 -0.467556  ...  0.586829  0.594078 -0.252120   
982  -0.344351  1.127831  1.165825  ... -0.055211 -0.306805  0.069768   
983   0.596518  0.510381 -1.041492  ... -0.303795 -0.893263 -0.008916   

          V24       V25       V26       V27       V28  Amount  Class  
0    0.558419 -0.027898  0.354254  0.273329 -0.152908    0.00      1  
1    0.497676 -0.375948  0.116118  0.228163  0.085428    0.69      0  
2    0.292539 -0.144967 -0.251744  1.249414 -0.131525  238.90      1  
3   -0.092984 -0.284045  0.761343 -0.068649 -0.055370   49.87      0  
4    0.245289 -0.230480  0.760068 -0.310989 -0.078149    7.68      0  
..        ...       ...       ...       ...       ...     ...    ...  
979  0.067038 -0.536600  0.115581  0.242770  0.088068    0.89      0  
980 -0.927246  0.454492 -0.638208  0.262021  0.034329   96.39      0  
981  0.325439  0.562766 -0.256278  0.652674  0.319879   67.90      1  
982  0.745159 -0.457676 -0.906335 -0.286269 -0.161240   12.05      0  
983 -0.032672  0.171486 -0.739786  0.134134 -0.029447   17.90      0  

[984 rows x 31 columns]

In [58]:
new_df.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      97195.817073 -0.060636  0.042503  0.097294 -0.005400  0.061133   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0     -0.031913 -0.031761 -0.076137 -0.002516  ... -0.024602  0.001798   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23      V24       V25       V26       V27       V28  \
Class                                                                        
0      0.015984  0.036542 -0.00514 -0.070069  0.006021 -0.016455 -0.012067   
1      0.014049 -0.040308 -0.10513  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       76.066646  
1      122.211321  

[2 rows x 30 columns]

In [56]:
new_df['Class'].value_counts()

Class
1    492
0    492
Name: count, dtype: int64

In [60]:
X=new_df.drop('Class', axis=1)
y=new_df['Class']

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

rf = RandomForestClassifier().fit(X_train,y_train)

In [71]:
rf = RandomForestClassifier().fit(X_train,y_train)

In [75]:
y_pred = rf.predict(X_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
      dtype=int64)

In [77]:
confusion_matrix(y_test,y_pred)

array([[97,  2],
       [ 7, 91]], dtype=int64)

In [79]:
TP = 91
FP = 2
FN = 7
TN = 97

accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1 = 2 * (precision * recall) / (precision + recall)

print(f"Accuracy:  {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall:    {recall:.2f}")
print(f"F1 Score:  {f1:.2f}")

Accuracy:  0.95
Precision: 0.98
Recall:    0.93
F1 Score:  0.95


In [81]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression().fit(X_train,y_train)

C:\Users\prajualr\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [83]:
y_pred1 = lr.predict(X_test)
y_pred1



array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
      dtype=int64)

In [85]:
confusion_matrix(y_test,y_pred1)

array([[98,  1],
       [ 6, 92]], dtype=int64)

In [87]:
TP = 92
FP = 1
FN = 6
TN = 98

accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
f1 = 2 * (precision * recall) / (precision + recall)

print(f"Accuracy:  {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall:    {recall:.2f}")
print(f"F1 Score:  {f1:.2f}")

Accuracy:  0.96
Precision: 0.99
Recall:    0.94
F1 Score:  0.96
